name: Develop Branch Pull Requests Check

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  setup:
    name: Common Setup
    uses: ./.github/workflows/common-setup.yml

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

  openapi-generate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI client
        run: npm run openapi:client

      - name: Upload OpenAPI client
        uses: actions/upload-artifact@v3
        with:
          name: openapi-client
          path: ./libs/openapi/src

  build:
    runs-on: ubuntu-latest
    needs: [lint, openapi-generate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Download OpenAPI client
        uses: actions/download-artifact@v3
        with:
          name: openapi-client
          path: ./libs/openapi/src

      - name: Build project
        run: npm run build