name: Develop Branch Deploy

on:
  push:
    branches:
      - develop

jobs:
  setup:
    name: Common Setup
    uses: ./.github/workflows/common-setup.yml

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

  openapi-generate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI client
        run: npm run openapi:client

      - name: Upload OpenAPI client
        uses: actions/upload-artifact@v3
        with:
          name: openapi-client
          path: ./libs/openapi/src

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, openapi-generate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node modules cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Download OpenAPI client
        uses: actions/download-artifact@v3
        with:
          name: openapi-client
          path: ./libs/openapi/src

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          publish_branch: publish
          publish_dir: ./dist/talent_match_frontend/browser

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
