name: Develop Branch Pull Requests Check

on:
  pull_request:
    branches:
      - develop

jobs:
  openapi-generate:
    runs-on: ubuntu-latest
    steps:
      - run: npm run openapi:client
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run eslint
